export const countries = [
  { name: "Afeganistão", code: "AF" },
  { name: "Ilhas Aland", code: "AX" },
  { name: "Albânia", code: "AL" },
  { name: "Argélia", code: "DZ" },
  { name: "Samoa Americana", code: "AS" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antártida", code: "AQ" },
  { name: "Antígua e Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armênia", code: "AM" },
  { name: "Arubano", code: "AW" },
  { name: "Austrália", code: "AU" },
  { name: "Áustria", code: "AT" },
  { name: "Azerbaijão", code: "AZ" },
  { name: "Bahrein", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Bélgica", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermudas", code: "BM" },
  { name: "Butão", code: "BT" },
  { name: "Bolívia", code: "BO" },
  { name: "Bonaire, Sint Eustatius e Saba", code: "BQ" },
  { name: "Bósnia-Herzegovina", code: "BA" },
  { name: "Botsuana", code: "BW" },
  { name: "Ilha Bouvet", code: "BV" },
  { name: "Brasil", code: "BR" },
  { name: "Território Britânico do Oceano Índico", code: "IO" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgária", code: "BG" },
  { name: "Burkina Fasso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Camboja", code: "KH" },
  { name: "Camarões", code: "CM" },
  { name: "Canadá", code: "CA" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Ilhas Caimão", code: "KY" },
  { name: "Central Africano República", code: "CF" },
  { name: "Chade", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Ilhas Natal", code: "CX" },
  { name: "Ilhas Cocos", code: "CC" },
  { name: "Colômbia", code: "CO" },
  { name: "Comores", code: "KM" },
  { name: "República do Congo", code: "CG" },
  { name: "Ilhas Cook", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Costa do Marfim", code: "CI" },
  { name: "Croácia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Curaçao", code: "CW" },
  { name: "Chipre", code: "CY" },
  { name: "República Tcheca", code: "CZ" },
  { name: "República Democrática do Congo", code: "CD" },
  { name: "Dinamarca", code: "DK" },
  { name: "Djibuti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "República Dominicana", code: "DO" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Equador", code: "EC" },
  { name: "Egito", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Guiné Equatorial", code: "GQ" },
  { name: "Eritréia", code: "ER" },
  { name: "Estónia", code: "EE" },
  { name: "Etiópia", code: "ET" },
  { name: "Ilhas Malvinas", code: "FK" },
  { name: "Ilhas Faroé", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finlândia", code: "FI" },
  { name: "França", code: "FR" },
  { name: "Guiana Francesa", code: "GF" },
  { name: "Polinésia Francesa", code: "PF" },
  { name: "Territórios Franceses do Sul", code: "TF" },
  { name: "Gabão", code: "GA" },
  { name: "Gâmbia", code: "GM" },
  { name: "Geórgia", code: "GE" },
  { name: "Alemanha", code: "DE" },
  { name: "Gana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Grécia", code: "GR" },
  { name: "Groenlândia", code: "GL" },
  { name: "Granada", code: "GD" },
  { name: "Guadalupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guiné", code: "GN" },
  { name: "GuinéBissau", code: "GW" },
  { name: "Guiana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Ilha Heard e Ilhas McDonald", code: "HM" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungria", code: "HU" },
  { name: "Islândia", code: "IS" },
  { name: "Índia", code: "IN" },
  { name: "Indonésia", code: "ID" },
  { name: "Irã", code: "IR" },
  { name: "Iraque", code: "IQ" },
  { name: "Irlanda", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Itália", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japão", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordânia", code: "JO" },
  { name: "Casaquistão", code: "KZ" },
  { name: "Quênia", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kosovo", code: "XK" },
  { name: "Kuwait]", code: "KW" },
  { name: "Quirguistão", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Letónia", code: "LV" },
  { name: "Líbano", code: "LB" },
  { name: "Lesoto", code: "LS" },
  { name: "Libéria", code: "LR" },
  { name: "Líbia", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lituânia", code: "LT" },
  { name: "Luxemburgo", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malásia", code: "MY" },
  { name: "Maldivas", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Man (Ilha de)", code: "IM" },
  { name: "Ilhas Marshall", code: "MH" },
  { name: "Martinica", code: "MQ" },
  { name: "Mauritânia", code: "MR" },
  { name: "Maurício", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "México", code: "MX" },
  { name: "Micronésia", code: "FM" },
  { name: "Moldávia", code: "MD" },
  { name: "Mônaco", code: "MC" },
  { name: "Mongólia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Marrocos", code: "MA" },
  { name: "Moçambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namíbia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Holanda", code: "NL" },
  { name: "Nova Caledônia", code: "NC" },
  { name: "Nova Zelândia", code: "NZ" },
  { name: "Nicarágua", code: "NI" },
  { name: "Níger", code: "NE" },
  { name: "Nigéria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Ilha Norfolk", code: "NF" },
  { name: "Coréia do Norte", code: "KP" },
  { name: "Macedônia do Norte", code: "MK" },
  { name: "Ilhas Marianas do Norte", code: "MP" },
  { name: "Noruega", code: "NO" },
  { name: "Omã", code: "OM" },
  { name: "Paquistão", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestina", code: "PS" },
  { name: "Panamá", code: "PA" },
  { name: "Papua Nova Guiné", code: "PG" },
  { name: "Paraguai", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Filipinas", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Polônia", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Porto Rico", code: "PR" },
  { name: "Catar", code: "QA" },
  { name: "Ilha Reunião", code: "RE" },
  { name: "Roménia", code: "RO" },
  { name: "Rússia", code: "RU" },
  { name: "Ruanda", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "São Cristóvão e Névis", code: "KN" },
  { name: "Santa Lúcia", code: "LC" },
  { name: "Saint Pierre e Miquelon", code: "PM" },
  { name: "São Vicente e Granadinas", code: "VC" },
  { name: "São Bartolomeu", code: "BL" },
  { name: "Saint-Martin (parte francesa)", code: "MF" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "São Tomé e Príncipe", code: "ST" },
  { name: "Arábia Saudita", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Sérvia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Serra Leoa", code: "SL" },
  { name: "Cingapura", code: "SG" },
  { name: "Sint Maarten (parte holandesa)", code: "SX" },
  { name: "Eslováquia", code: "SK" },
  { name: "Eslovênia", code: "SI" },
  { name: "Ilhas Salomão", code: "SB" },
  { name: "Somália", code: "SO" },
  { name: "África do Sul", code: "ZA" },
  { name: "Geórgia do Sul e Ilhas Sandwich do Sul", code: "GS" },
  { name: "Coréia do Sul", code: "KR" },
  { name: "Sudão do Sul", code: "SS" },
  { name: "Espanha", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudão", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard e Jan Mayen", code: "SJ" },
  { name: "Essuatíni", code: "SZ" },
  { name: "Suécia", code: "SE" },
  { name: "Suíça", code: "CH" },
  { name: "Síria", code: "SY" },
  { name: "Taiwan", code: "TW" },
  { name: "Tadjiquistão", code: "TJ" },
  { name: "Tanzânia", code: "TZ" },
  { name: "Tailândia", code: "TH" },
  { name: "Bahamas", code: "BS" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad e Tobago", code: "TT" },
  { name: "Tunísia", code: "TN" },
  { name: "Turquia", code: "TR" },
  { name: "Turcomenistão", code: "TM" },
  { name: "Ilhas Turks e Caicos", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ucrânia", code: "UA" },
  { name: "Emirados Árabes Unidos", code: "AE" },
  { name: "Reino Unido", code: "GB" },
  { name: "Estados Unidos", code: "US" },
  { name: "Territórios Insulares dos Estados Unidos", code: "UM" },
  { name: "Uruguai", code: "UY" },
  { name: "Uzbequistão", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Vaticano", code: "VA" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnã", code: "VN" },
  { name: "Ilhas Virgens Britânicas", code: "VG" },
  { name: "Ilhas Virgens", code: "VI" },
  { name: "Wallis e Futuna", code: "WF" },
  { name: "Saara Ocidental", code: "EH" },
  { name: "Iêmen", code: "YE" },
  { name: "Zâmbia", code: "ZM" },
  { name: "Zimbábue", code: "ZW" },
].sort((a, b) => a.name.localeCompare(b.name));

export const countriesOptions = countries.map((country) => ({
  value: country.name,
  label: country.name,
  code: country.code,
}));
