/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PrivateRouteImport } from './app/_private'
import { Route as PrivateIndexRouteImport } from './app/_private/index'
import { Route as PublicAuthRouteImport } from './app/_public/_auth'
import { Route as PrivatePerfilRouteImport } from './app/_private/perfil'
import { Route as PrivateUsuariosIndexRouteImport } from './app/_private/usuarios/index'
import { Route as PrivateNivelAcessoIndexRouteImport } from './app/_private/nivel-acesso/index'
import { Route as PrivateUsuariosCriarRouteImport } from './app/_private/usuarios/criar'
import { Route as PrivateUsuariosUser_idRouteImport } from './app/_private/usuarios/$user_id'
import { Route as PrivateNivelAcessoCriarRouteImport } from './app/_private/nivel-acesso/criar'
import { Route as PrivateNivelAcessoAccess_profile_idRouteImport } from './app/_private/nivel-acesso/$access_profile_id'
import { Route as PublicAuthRedefinirSenhaIndexRouteImport } from './app/_public/_auth/redefinir-senha/index'
import { Route as PublicAuthLoginIndexRouteImport } from './app/_public/_auth/login/index'
import { Route as PublicAuthEsqueciSenhaIndexRouteImport } from './app/_public/_auth/esqueci-senha/index'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_public/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatePerfilRoute = PrivatePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsuariosIndexRoute = PrivateUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateNivelAcessoIndexRoute = PrivateNivelAcessoIndexRouteImport.update({
  id: '/nivel-acesso/',
  path: '/nivel-acesso/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsuariosCriarRoute = PrivateUsuariosCriarRouteImport.update({
  id: '/usuarios/criar',
  path: '/usuarios/criar',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsuariosUser_idRoute = PrivateUsuariosUser_idRouteImport.update({
  id: '/usuarios/$user_id',
  path: '/usuarios/$user_id',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateNivelAcessoCriarRoute = PrivateNivelAcessoCriarRouteImport.update({
  id: '/nivel-acesso/criar',
  path: '/nivel-acesso/criar',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateNivelAcessoAccess_profile_idRoute =
  PrivateNivelAcessoAccess_profile_idRouteImport.update({
    id: '/nivel-acesso/$access_profile_id',
    path: '/nivel-acesso/$access_profile_id',
    getParentRoute: () => PrivateRoute,
  } as any)
const PublicAuthRedefinirSenhaIndexRoute =
  PublicAuthRedefinirSenhaIndexRouteImport.update({
    id: '/redefinir-senha/',
    path: '/redefinir-senha/',
    getParentRoute: () => PublicAuthRoute,
  } as any)
const PublicAuthLoginIndexRoute = PublicAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthEsqueciSenhaIndexRoute =
  PublicAuthEsqueciSenhaIndexRouteImport.update({
    id: '/esqueci-senha/',
    path: '/esqueci-senha/',
    getParentRoute: () => PublicAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/perfil': typeof PrivatePerfilRoute
  '/nivel-acesso/$access_profile_id': typeof PrivateNivelAcessoAccess_profile_idRoute
  '/nivel-acesso/criar': typeof PrivateNivelAcessoCriarRoute
  '/usuarios/$user_id': typeof PrivateUsuariosUser_idRoute
  '/usuarios/criar': typeof PrivateUsuariosCriarRoute
  '/nivel-acesso/': typeof PrivateNivelAcessoIndexRoute
  '/usuarios/': typeof PrivateUsuariosIndexRoute
  '/esqueci-senha/': typeof PublicAuthEsqueciSenhaIndexRoute
  '/login/': typeof PublicAuthLoginIndexRoute
  '/redefinir-senha/': typeof PublicAuthRedefinirSenhaIndexRoute
}
export interface FileRoutesByTo {
  '/perfil': typeof PrivatePerfilRoute
  '/': typeof PrivateIndexRoute
  '/nivel-acesso/$access_profile_id': typeof PrivateNivelAcessoAccess_profile_idRoute
  '/nivel-acesso/criar': typeof PrivateNivelAcessoCriarRoute
  '/usuarios/$user_id': typeof PrivateUsuariosUser_idRoute
  '/usuarios/criar': typeof PrivateUsuariosCriarRoute
  '/nivel-acesso': typeof PrivateNivelAcessoIndexRoute
  '/usuarios': typeof PrivateUsuariosIndexRoute
  '/esqueci-senha': typeof PublicAuthEsqueciSenhaIndexRoute
  '/login': typeof PublicAuthLoginIndexRoute
  '/redefinir-senha': typeof PublicAuthRedefinirSenhaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_private/perfil': typeof PrivatePerfilRoute
  '/_public/_auth': typeof PublicAuthRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/_private/nivel-acesso/$access_profile_id': typeof PrivateNivelAcessoAccess_profile_idRoute
  '/_private/nivel-acesso/criar': typeof PrivateNivelAcessoCriarRoute
  '/_private/usuarios/$user_id': typeof PrivateUsuariosUser_idRoute
  '/_private/usuarios/criar': typeof PrivateUsuariosCriarRoute
  '/_private/nivel-acesso/': typeof PrivateNivelAcessoIndexRoute
  '/_private/usuarios/': typeof PrivateUsuariosIndexRoute
  '/_public/_auth/esqueci-senha/': typeof PublicAuthEsqueciSenhaIndexRoute
  '/_public/_auth/login/': typeof PublicAuthLoginIndexRoute
  '/_public/_auth/redefinir-senha/': typeof PublicAuthRedefinirSenhaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/perfil'
    | '/nivel-acesso/$access_profile_id'
    | '/nivel-acesso/criar'
    | '/usuarios/$user_id'
    | '/usuarios/criar'
    | '/nivel-acesso/'
    | '/usuarios/'
    | '/esqueci-senha/'
    | '/login/'
    | '/redefinir-senha/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/perfil'
    | '/'
    | '/nivel-acesso/$access_profile_id'
    | '/nivel-acesso/criar'
    | '/usuarios/$user_id'
    | '/usuarios/criar'
    | '/nivel-acesso'
    | '/usuarios'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
  id:
    | '__root__'
    | '/_private'
    | '/_private/perfil'
    | '/_public/_auth'
    | '/_private/'
    | '/_private/nivel-acesso/$access_profile_id'
    | '/_private/nivel-acesso/criar'
    | '/_private/usuarios/$user_id'
    | '/_private/usuarios/criar'
    | '/_private/nivel-acesso/'
    | '/_private/usuarios/'
    | '/_public/_auth/esqueci-senha/'
    | '/_public/_auth/login/'
    | '/_public/_auth/redefinir-senha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/perfil': {
      id: '/_private/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PrivatePerfilRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/usuarios/': {
      id: '/_private/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof PrivateUsuariosIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/nivel-acesso/': {
      id: '/_private/nivel-acesso/'
      path: '/nivel-acesso'
      fullPath: '/nivel-acesso/'
      preLoaderRoute: typeof PrivateNivelAcessoIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/usuarios/criar': {
      id: '/_private/usuarios/criar'
      path: '/usuarios/criar'
      fullPath: '/usuarios/criar'
      preLoaderRoute: typeof PrivateUsuariosCriarRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/usuarios/$user_id': {
      id: '/_private/usuarios/$user_id'
      path: '/usuarios/$user_id'
      fullPath: '/usuarios/$user_id'
      preLoaderRoute: typeof PrivateUsuariosUser_idRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/nivel-acesso/criar': {
      id: '/_private/nivel-acesso/criar'
      path: '/nivel-acesso/criar'
      fullPath: '/nivel-acesso/criar'
      preLoaderRoute: typeof PrivateNivelAcessoCriarRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/nivel-acesso/$access_profile_id': {
      id: '/_private/nivel-acesso/$access_profile_id'
      path: '/nivel-acesso/$access_profile_id'
      fullPath: '/nivel-acesso/$access_profile_id'
      preLoaderRoute: typeof PrivateNivelAcessoAccess_profile_idRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/_auth/redefinir-senha/': {
      id: '/_public/_auth/redefinir-senha/'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha/'
      preLoaderRoute: typeof PublicAuthRedefinirSenhaIndexRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/login/': {
      id: '/_public/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicAuthLoginIndexRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/esqueci-senha/': {
      id: '/_public/_auth/esqueci-senha/'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha/'
      preLoaderRoute: typeof PublicAuthEsqueciSenhaIndexRouteImport
      parentRoute: typeof PublicAuthRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivatePerfilRoute: typeof PrivatePerfilRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateNivelAcessoAccess_profile_idRoute: typeof PrivateNivelAcessoAccess_profile_idRoute
  PrivateNivelAcessoCriarRoute: typeof PrivateNivelAcessoCriarRoute
  PrivateUsuariosUser_idRoute: typeof PrivateUsuariosUser_idRoute
  PrivateUsuariosCriarRoute: typeof PrivateUsuariosCriarRoute
  PrivateNivelAcessoIndexRoute: typeof PrivateNivelAcessoIndexRoute
  PrivateUsuariosIndexRoute: typeof PrivateUsuariosIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivatePerfilRoute: PrivatePerfilRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateNivelAcessoAccess_profile_idRoute:
    PrivateNivelAcessoAccess_profile_idRoute,
  PrivateNivelAcessoCriarRoute: PrivateNivelAcessoCriarRoute,
  PrivateUsuariosUser_idRoute: PrivateUsuariosUser_idRoute,
  PrivateUsuariosCriarRoute: PrivateUsuariosCriarRoute,
  PrivateNivelAcessoIndexRoute: PrivateNivelAcessoIndexRoute,
  PrivateUsuariosIndexRoute: PrivateUsuariosIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicAuthRouteChildren {
  PublicAuthEsqueciSenhaIndexRoute: typeof PublicAuthEsqueciSenhaIndexRoute
  PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
  PublicAuthRedefinirSenhaIndexRoute: typeof PublicAuthRedefinirSenhaIndexRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthEsqueciSenhaIndexRoute: PublicAuthEsqueciSenhaIndexRoute,
  PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute,
  PublicAuthRedefinirSenhaIndexRoute: PublicAuthRedefinirSenhaIndexRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicAuthRoute: PublicAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
